// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbvezdhokmsflzrrmenz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtidmV6ZGhva21zZmx6cnJtZW56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNzM2NzIsImV4cCI6MjA1Njg0OTY3Mn0.YYZO2_HUFT0Wl5IjYo8xddz5A9SILVfA-HDSMkGuFg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);